/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package mainGUIs;

import implementations.StudentDAOImpl;
import implementations.UserDAOImpl;
import javax.swing.JOptionPane;
import models.Student;
import models.User;

/**
 *
 * @author NelsonJrLHerrera
 */
public class StudentInfo extends java.awt.Dialog {

    UserDAOImpl userDAOImpl = new UserDAOImpl();
    StudentDAOImpl studentDAOImpl = new StudentDAOImpl();
    Student student = null;
    private final User user;

    /**
     * Creates new form StudentInfo
     */
    public StudentInfo(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        lrnTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        classCB = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Information"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Grade & Section:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        backBTN.setBackground(new java.awt.Color(204, 204, 204));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        addBTN.setBackground(new java.awt.Color(204, 204, 204));
        addBTN.setText("Add Student");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        jPanel1.add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        jPanel1.add(lrnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 260, 30));

        jLabel3.setText("LRN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        classCB.setBackground(new java.awt.Color(204, 204, 204));
        classCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11-ICT", "11-ABM", "11-HE1", "11-HE2A", "11-HE2B", "11-HUMMS", "11-STEM", "12-ABM", "12-HE1", "12-HE2A", "12-HE2B", "12-HUMMS", "12-ICT", "12-STEM" }));
        classCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classCBActionPerformed(evt);
            }
        });
        jPanel1.add(classCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 260, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure to discard the infos above and remove the User account?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == 0) {
            if(userDAOImpl.deleteUser(this.user.getUserId()) == true){
               JOptionPane.showMessageDialog(this, "User and Student deleted successfully", "Notification", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "User not deleted. An error occured.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_backBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String lrn = lrnTF.getText();
        String grade_section = classCB.getSelectedItem().toString();
        int grade = Integer.parseInt(grade_section.substring(0, 2));
        String section = grade_section.substring(3);
        int classId = classCB.getSelectedIndex() + 20;

        if (!lrn.isEmpty() && lrn.length() == 12) {
            student = new Student(-1, this.user.getUserId(), Long.parseLong(lrn), grade, section, classId, "", "", "");
            
            if (studentDAOImpl.create(student)) {
                JOptionPane.showMessageDialog(this, "User and Student added successfully", "Notification", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // Close dialog after success
            } else {
                userDAOImpl.deleteUser(this.user.getUserId());
                JOptionPane.showMessageDialog(this, "User added, but failed to add student.", "Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Input a valid LRN", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void classCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentInfo dialog = new StudentInfo(new java.awt.Frame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JComboBox<String> classCB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lrnTF;
    // End of variables declaration//GEN-END:variables
}
