/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package mainGUIs;

import implementations.StudentDAOImpl;
import implementations.UserDAOImpl;
import javax.swing.JOptionPane;
import models.Student;

/**
 *
 * @author NelsonJrLHerrera
 */
public class StudentInfo extends java.awt.Dialog {
    UserDAOImpl userDAOImpl = new UserDAOImpl();
    StudentDAOImpl studentDAOImpl = new StudentDAOImpl();
    AdminGUI adminGUI = new AdminGUI();
    Student student = null;
    /**
     * Creates new form StudentInfo
     */
    public StudentInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        gradeCB = new javax.swing.JComboBox<>();
        sectionCB = new javax.swing.JComboBox<>();
        lrnTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Information"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Grade:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setText("Section:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        backBTN.setBackground(new java.awt.Color(204, 204, 204));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        addBTN.setBackground(new java.awt.Color(204, 204, 204));
        addBTN.setText("Add Student");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        jPanel1.add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        gradeCB.setBackground(new java.awt.Color(204, 204, 204));
        gradeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));
        jPanel1.add(gradeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 30));

        sectionCB.setBackground(new java.awt.Color(204, 204, 204));
        sectionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABM", "HE1", "HE2A", "HE2B", "HUMMS", "STEM" }));
        jPanel1.add(sectionCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, 30));
        jPanel1.add(lrnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 260, 30));

        jLabel3.setText("LRN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure to discard the infos above?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);
        
        if(option == 0){
            this.dispose();
        }
    }//GEN-LAST:event_backBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String lrn = lrnTF.getText();
        String grade = gradeCB.getSelectedItem().toString();
        String section = sectionCB.getSelectedItem().toString();
        
        if(!(lrnTF.getText().isEmpty() && lrn.length() < 12)){
            userDAOImpl.addUser(adminGUI.user);
            student = 
            studentDAOImpl.create(student);
        }else{
            JOptionPane.showMessageDialog(this, "Input a valid LRN", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentInfo dialog = new StudentInfo(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JComboBox<String> gradeCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lrnTF;
    private javax.swing.JComboBox<String> sectionCB;
    // End of variables declaration//GEN-END:variables
}
