/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mainGUIs;

import implementations.ClassesDAOImpl;
import implementations.TeacherDAOImpl;
import implementations.UserDAOImpl;
import javax.swing.JOptionPane;
import models.Teacher;
import models.User;
import models.Classes;

/**
 *
 * @author HansBVitorillo
 */
public class Teacher_Info extends javax.swing.JDialog {

    UserDAOImpl userDAOImpl = new UserDAOImpl();
    TeacherDAOImpl teacherDAOImpl = new TeacherDAOImpl();
    ClassesDAOImpl classesDAOImpl = new ClassesDAOImpl();
    Teacher teacher;
    Classes classes;
    private User user;

    /**
     * Creates new form Teacher_Info
     */
    public Teacher_Info(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        advisoryCB = new javax.swing.JComboBox<>();
        addTeacherBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Teacher Information"));

        jLabel2.setText("Advisory:");

        advisoryCB.setBackground(new java.awt.Color(204, 204, 204));
        advisoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "11-ICT", "11-ABM", "11-HE1", "11-HE2A", "11-HE2B", "11-HUMMS", "11-STEM", "12-ABM", "12-HE1", "12-HE2A", "12-HE2B", "12-HUMMS", "12-ICT", "12-STEM" }));
        advisoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advisoryCBActionPerformed(evt);
            }
        });

        addTeacherBTN.setBackground(new java.awt.Color(204, 204, 204));
        addTeacherBTN.setText("Add Teacher");
        addTeacherBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherBTNActionPerformed(evt);
            }
        });

        backBTN.setBackground(new java.awt.Color(204, 204, 204));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(advisoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addTeacherBTN)
                .addGap(18, 18, 18)
                .addComponent(backBTN)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(advisoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTeacherBTN)
                    .addComponent(backBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void advisoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advisoryCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advisoryCBActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Are you sure to discard the infos above and remove the User account?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);

        if (option == 0) {
            if (userDAOImpl.deleteUser(this.user.getUserId()) == true) {
                JOptionPane.showMessageDialog(this, "User and Teacher deleted successfully", "Notification", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "User not deleted. An error occured.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_backBTNActionPerformed

    private void addTeacherBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherBTNActionPerformed
        // TODO add your handling code here:
        String advisory = advisoryCB.getSelectedItem().toString();
        int grade = Integer.parseInt(advisory.substring(0, 2));
        String section = advisory.substring(3);

        if (!"None".equals(advisory)) {

            if (classesDAOImpl.existsWithAdviser(grade, section)) {
                JOptionPane.showMessageDialog(this, "This class already has an assigned adviser.", "Error", JOptionPane.ERROR_MESSAGE);
                userDAOImpl.deleteUser(this.user.getUserId()); // Clean up newly added user
                this.dispose();
                return; // Stop the method
            }

            teacher = new Teacher(-1, this.user.getUserId(), advisory, "", "");

            Integer teacher_id = teacherDAOImpl.createTeacher(teacher);
            if (teacher_id != null) {
                JOptionPane.showMessageDialog(this, "User and Teacher added successfully", "Notification", JOptionPane.INFORMATION_MESSAGE);

                this.teacher.setTeacherId(teacher_id);
                classes = new Classes(-1, this.teacher.getTeacherId(), grade, section, "", "");
                if (classesDAOImpl.create(classes) == true) {
                    JOptionPane.showMessageDialog(this, "New class added.", "Notification", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "User and Teacher added, but failed to add new Class Advisory. User and Teacher deleted.", "Error", JOptionPane.ERROR_MESSAGE);
                    teacherDAOImpl.deleteTeacher(this.teacher.getTeacherId());
                    userDAOImpl.deleteUser(this.user.getUserId());
                    this.dispose();
                }

                this.dispose(); // Close dialog after success
            } else {
                userDAOImpl.deleteUser(this.user.getUserId());
                JOptionPane.showMessageDialog(this, "User added, but failed to add Teacher. User deleted.", "Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        }else{
            teacher = new Teacher(-1, this.user.getUserId(), advisory, "", "");
            Integer teacher_id = teacherDAOImpl.createTeacher(teacher);
            if (teacher_id != null) {
                JOptionPane.showMessageDialog(this, "User and Teacher added successfully", "Notification", JOptionPane.INFORMATION_MESSAGE);

                this.teacher.setTeacherId(teacher_id);
            }else{
                userDAOImpl.deleteUser(this.user.getUserId());
                JOptionPane.showMessageDialog(this, "User added, but failed to add Teacher. User deleted.", "Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_addTeacherBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Teacher_Info dialog = new Teacher_Info(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeacherBTN;
    private javax.swing.JComboBox<String> advisoryCB;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
